### ISSUE TITLE
Does GPytorch perform a lot of speedups over GPy or MATLAB's Gaussian Process?

### ISSUE THREAD

**Issue by yxchng** [jrg365/gpytorch#2]
Just wondering, is this project just a hobby project to learn more about GP or does it provide a lot of speedups over existing GP library? I would expect so since it uses GPU. Is that right?

**Comment by gpleiss** [comment]
The goal for this library is speed an modularity!

Right now, we're still in the early development phase, so our main focus has been the interface and modularity. Now that the interface is more or less developed, our next goal is making major speed improvements and adding documentation.

Since we're using PyTorch, our library supports GPU use. (We haven't tested it thoroughly yet, but it should work! Let us know if there are issues.)
